-- Hope & Heart CMS upgrade: run after the existing schema files.
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'Community',
  image text not null,
  caption text default '',
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  bio text default '',
  image text not null,
  email text default '',
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  logo text not null,
  website text default '',
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.gallery enable row level security;
alter table public.team_members enable row level security;
alter table public.partners enable row level security;

drop policy if exists "Public reads gallery" on public.gallery;
create policy "Public reads gallery" on public.gallery for select to anon, authenticated using (published=true);
drop policy if exists "Public reads team" on public.team_members;
create policy "Public reads team" on public.team_members for select to anon, authenticated using (published=true);
drop policy if exists "Public reads partners" on public.partners;
create policy "Public reads partners" on public.partners for select to anon, authenticated using (published=true);

insert into public.settings(key,value) values
('logo_url',''),('favicon_url',''),('hero_image','https://images.unsplash.com/photo-1489493585363-d69421e0edd3?auto=format&fit=crop&w=1500&q=88'),
('about_title','We Are Here to Create Lasting Change'),('about_text','Hope & Heart Foundation is a non-profit organization working to improve lives and build stronger communities through education, health, environment, and livelihood programs.'),
('about_image','https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1200&q=85'),
('whatsapp',''),('map_url',''),('facebook',''),('instagram',''),('youtube',''),('linkedin',''),
('upi_id',''),('donation_qr_url',''),('minimum_donation','100'),('receipt_name','Hope & Heart Foundation'),
('footer_text','Together, let’s build a better world for today and tomorrow.'),
('seo_title','Hope & Heart Foundation'),('seo_description','Support transparent, community-led programs in education, healthcare, environment and livelihoods.'),
('primary_color','#149447'),('show_gallery','true'),('show_team','true'),('show_partners','true')
on conflict(key) do nothing;

insert into public.gallery(title,category,image,caption,sort_order)
select * from (values
('Learning Together','Education','https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=82','Children participating in a community learning session.',1),
('Health Outreach','Healthcare','https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=900&q=82','A rural health outreach programme.',2),
('Green Communities','Environment','https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=900&q=82','Volunteers supporting local environmental action.',3)
) as x(title,category,image,caption,sort_order) where not exists(select 1 from public.gallery);

insert into public.team_members(name,role,bio,image,sort_order)
select * from (values
('Priya Sharma','Program Director','Leads community programmes and impact measurement.','https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=80',1),
('Arjun Das','Volunteer Coordinator','Builds meaningful volunteer partnerships across Assam.','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',2)
) as x(name,role,bio,image,sort_order) where not exists(select 1 from public.team_members);

insert into public.partners(name,logo,website,sort_order)
select * from (values
('Community Partner','https://dummyimage.com/240x100/f1f5f3/145c37&text=Community+Partner','',1),
('Education Alliance','https://dummyimage.com/240x100/f1f5f3/145c37&text=Education+Alliance','',2)
) as x(name,logo,website,sort_order) where not exists(select 1 from public.partners);

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('site-media','site-media',true,5242880,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=true,file_size_limit=5242880,allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif'];
