-- Hope & Heart NGO CMS
-- Complete, idempotent Supabase schema/migration
-- Safe to run more than once in Supabase SQL Editor.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Core tables
-- ---------------------------------------------------------------------------

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value text not null default ''
);

create table if not exists public.causes (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  image text not null,
  raised numeric(12,2) not null default 0 check (raised >= 0),
  goal numeric(12,2) not null default 1 check (goal > 0),
  status text not null default 'Active',
  featured boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  quote text not null,
  image text not null,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_date timestamptz not null,
  location text not null,
  description text not null,
  image text not null,
  capacity integer not null default 100 check (capacity > 0),
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'News',
  summary text not null,
  content text not null default '',
  image text not null,
  link text not null default '',
  published boolean not null default true,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'General',
  image text not null,
  caption text not null default '',
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  bio text not null default '',
  image text not null,
  email text not null default '',
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  logo text not null,
  website text not null default '',
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  donation_id text unique not null,
  donor_name text not null,
  email text not null,
  amount numeric(12,2) not null check (amount >= 100),
  frequency text not null default 'One-time',
  cause_id bigint references public.causes(id) on delete set null,
  anonymous boolean not null default false,
  status text not null default 'Pending',
  razorpay_order_id text unique,
  razorpay_payment_id text unique,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.volunteers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  interest text not null,
  message text not null default '',
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null default '',
  subject text not null,
  message text not null,
  status text not null default 'New',
  created_at timestamptz not null default now()
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Add any columns missing from older installations
-- ---------------------------------------------------------------------------

alter table public.causes
  add column if not exists featured boolean not null default true,
  add column if not exists status text not null default 'Active';

alter table public.stories
  add column if not exists published boolean not null default true;

alter table public.events
  add column if not exists published boolean not null default true;

alter table public.news
  add column if not exists category text not null default 'News',
  add column if not exists summary text not null default '',
  add column if not exists content text not null default '',
  add column if not exists image text not null default '',
  add column if not exists link text not null default '',
  add column if not exists published boolean not null default true,
  add column if not exists published_at timestamptz not null default now();

-- ---------------------------------------------------------------------------
-- Functions
-- ---------------------------------------------------------------------------

create or replace function public.increment_cause_raised(
  cause_row_id bigint,
  increment_amount numeric
)
returns void
language sql
security definer
set search_path = public
as $$
  update public.causes
  set raised = raised + greatest(coalesce(increment_amount, 0), 0)
  where id = cause_row_id;
$$;

revoke all on function public.increment_cause_raised(bigint, numeric) from public;
grant execute on function public.increment_cause_raised(bigint, numeric) to service_role;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

create index if not exists idx_causes_status
  on public.causes(status);

create index if not exists idx_causes_featured
  on public.causes(featured);

create index if not exists idx_events_published_date
  on public.events(published, event_date);

create index if not exists idx_news_published_date
  on public.news(published, published_at desc);

create index if not exists idx_gallery_published_sort
  on public.gallery(published, sort_order, id);

create index if not exists idx_team_published_sort
  on public.team_members(published, sort_order, id);

create index if not exists idx_partners_published_sort
  on public.partners(published, sort_order, id);

create index if not exists idx_donations_status_paid
  on public.donations(status, paid_at desc);

create index if not exists idx_donations_cause
  on public.donations(cause_id);

create index if not exists idx_volunteers_status
  on public.volunteers(status);

create index if not exists idx_contacts_status
  on public.contacts(status);

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- The Vercel API uses SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
-- Browser clients receive read-only public access to published content and
-- insert-only access to public forms. No public update/delete policies exist.
-- ---------------------------------------------------------------------------

alter table public.admin_users enable row level security;
alter table public.settings enable row level security;
alter table public.causes enable row level security;
alter table public.stories enable row level security;
alter table public.events enable row level security;
alter table public.news enable row level security;
alter table public.gallery enable row level security;
alter table public.team_members enable row level security;
alter table public.partners enable row level security;
alter table public.donations enable row level security;
alter table public.volunteers enable row level security;
alter table public.contacts enable row level security;
alter table public.subscribers enable row level security;

-- Drop only policies owned by this migration, then recreate them.

drop policy if exists "public_read_settings" on public.settings;
create policy "public_read_settings"
on public.settings for select
to anon, authenticated
using (true);

drop policy if exists "public_read_active_causes" on public.causes;
create policy "public_read_active_causes"
on public.causes for select
to anon, authenticated
using (status = 'Active');

drop policy if exists "public_read_published_stories" on public.stories;
create policy "public_read_published_stories"
on public.stories for select
to anon, authenticated
using (published = true);

drop policy if exists "public_read_published_events" on public.events;
create policy "public_read_published_events"
on public.events for select
to anon, authenticated
using (published = true);

drop policy if exists "public_read_published_news" on public.news;
create policy "public_read_published_news"
on public.news for select
to anon, authenticated
using (published = true);

drop policy if exists "public_read_published_gallery" on public.gallery;
create policy "public_read_published_gallery"
on public.gallery for select
to anon, authenticated
using (published = true);

drop policy if exists "public_read_published_team" on public.team_members;
create policy "public_read_published_team"
on public.team_members for select
to anon, authenticated
using (published = true);

drop policy if exists "public_read_published_partners" on public.partners;
create policy "public_read_published_partners"
on public.partners for select
to anon, authenticated
using (published = true);

drop policy if exists "public_create_volunteer" on public.volunteers;
create policy "public_create_volunteer"
on public.volunteers for insert
to anon, authenticated
with check (
  length(trim(name)) > 0
  and length(trim(email)) > 3
  and length(trim(phone)) > 0
  and length(trim(interest)) > 0
);

drop policy if exists "public_create_contact" on public.contacts;
create policy "public_create_contact"
on public.contacts for insert
to anon, authenticated
with check (
  length(trim(name)) > 0
  and length(trim(email)) > 3
  and length(trim(subject)) > 0
  and length(trim(message)) > 0
);

drop policy if exists "public_create_subscriber" on public.subscribers;
create policy "public_create_subscriber"
on public.subscribers for insert
to anon, authenticated
with check (length(trim(email)) > 3);

-- Donations are created and verified only through the server API.
-- No anon/authenticated donation policy is intentionally created.

-- ---------------------------------------------------------------------------
-- Storage bucket for CMS media
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-media',
  'site-media',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public_read_site_media" on storage.objects;
create policy "public_read_site_media"
on storage.objects for select
to public
using (bucket_id = 'site-media');

-- Uploads/deletes use the service role through the server API.
-- No public storage insert/update/delete policies are created.

-- ---------------------------------------------------------------------------
-- Default CMS settings
-- ---------------------------------------------------------------------------

insert into public.settings (key, value) values
  ('ngo_name', 'Hope & Heart Foundation'),
  ('email', 'info@hopeheart.org'),
  ('phone', '+91 98765 43210'),
  ('address', 'Garchuk, Guwahati, Assam'),
  ('whatsapp', ''),
  ('hero_title', 'A Better World Starts With You'),
  ('hero_text', 'We work in communities to bring hope, create opportunities, and improve lives. Be a part of the change today.'),
  ('hero_image', ''),
  ('about_title', 'We Are Here to Create Lasting Change'),
  ('about_text', ''),
  ('about_image', ''),
  ('logo', ''),
  ('favicon', ''),
  ('footer_logo', ''),
  ('footer_text', 'Together, let’s build a better world for today and tomorrow.'),
  ('facebook', ''),
  ('instagram', ''),
  ('youtube', ''),
  ('twitter', ''),
  ('linkedin', ''),
  ('map_url', ''),
  ('upi_id', ''),
  ('donation_qr', ''),
  ('minimum_donation', '100'),
  ('receipt_name', 'Hope & Heart Foundation'),
  ('seo_title', 'Hope & Heart Foundation'),
  ('seo_description', 'Supporting communities through education, healthcare and sustainable development.'),
  ('primary_color', '#0b8d43'),
  ('show_gallery', 'true'),
  ('show_team', 'true'),
  ('show_partners', 'true'),
  ('lives', '25000'),
  ('projects', '150'),
  ('volunteers', '500'),
  ('communities', '50')
on conflict (key) do nothing;

commit;

-- Optional verification queries:
-- select key, value from public.settings order by key;
-- select id, name, public from storage.buckets where id = 'site-media';
-- select tablename, policyname from pg_policies where schemaname = 'public';
