import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,BookOpen,CalendarDays,Check,ChevronLeft,ChevronRight,Clock,Heart,Leaf,LogOut,Mail,MapPin,Menu,Newspaper,Phone,Play,Plus,ShieldCheck,Sparkles,Target,Trash2,Users,X}from'lucide-react';
import'./styles.css';
const api = async (url, options = {}) => {
const token = localStorage.getItem('adminToken');
const response = await fetch(url, {
    ...options,
      cache: 'no-store',
headers: {
'Content-Type': 'application/json',
 ...(token
 ? { Authorization: `Bearer ${token}` }
 : {}),
...(options.headers || {})
 }
});
const responseText = await response.text();
let data = {};
try {
data = responseText ? JSON.parse(responseText) : {};
} catch {
throw new Error(
response.status === 404
? `API route not found: ${url}`
: 'The server returned an invalid response.'
);
}
if (!response.ok) {
throw new Error(
 data.error || `Request failed with status ${response.status}.`
);
}
return data;
};

const uploadImage = async (file) => {
  if (!file) throw new Error('Please select an image.');
  if (!String(file.type).startsWith('image/')) {
    throw new Error('Only image files are allowed.');
  }
  if (file.size > 4 * 1024 * 1024) {
    throw new Error('Image must be smaller than 4 MB.');
  }

  const base64 = await new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = () => reject(new Error('The selected image could not be read.'));
    reader.readAsDataURL(file);
  });

  return api('/api/admin/upload', {
    method: 'POST',
    body: JSON.stringify({
      file_name: file.name,
      content_type: file.type,
      base64
    })
  });
};
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
function App(){const[route,setRoute]=useState(location.hash||'#home');useEffect(()=>{const f=()=>setRoute(location.hash||'#home');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);return route.startsWith('#admin')?<Admin/>:<Site/>}
function Site(){const[data,setData]=useState({settings:{},causes:[],stories:[],events:[],news:[],gallery:[],team_members:[],partners:[],recentDonations:[],campaignSummary:{}}),[menu,setMenu]=useState(false),[donate,setDonate]=useState(null),[toast,setToast]=useState(''),[story,setStory]=useState(0);const load=()=>api('/api/public').then(setData).catch(()=>{});useEffect(()=>{load();const timer=setInterval(load,12000);const visible=()=>{if(document.visibilityState==='visible')load()};document.addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visible)}},[]);useEffect(()=>{const t=setInterval(()=>setStory(i=>data.stories.length?(i+1)%data.stories.length:0),5000);return()=>clearInterval(t)},[data.stories.length]);const notify=x=>{setToast(x);setTimeout(()=>setToast(''),3000)};const s=data.settings, current=data.stories[story];return <><div className="topbar"><span><Mail size={14}/> {s.email}</span><span><Phone size={14}/> {s.phone}</span><a href="#admin">Admin Login</a></div><header><a className="brand" href="#home"><b>♡</b><span>Hope & Heart<small>FOUNDATION</small></span></a><nav className={menu?'open':''}>{['Home','About','Our Work','Causes','Volunteer','Stories','Events','News','Contact'].map(x=><a key={x} href={`#${x.toLowerCase().replaceAll(' ','-')}`} onClick={()=>setMenu(false)}>{x}</a>)}</nav><button className="btn primary" onClick={()=>setDonate({})}>Donate Now ♥</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header><main>
<section id="home" className="hero"><div><span className="eyebrow"><Sparkles/> Together we can</span><h1>{s.hero_title||'A Better World Starts With You'}</h1><p>{s.hero_text}</p><div className="actions"><button className="btn primary" onClick={()=>setDonate({})}>Donate Now ♥</button><a className="btn ghost" href="#causes">Explore Our Work <ArrowRight/></a></div><div className="support"><div>👩🏽‍🦱👨🏽‍🦱👩🏻👨🏻</div><b>Join 10,000+ people<br/><small>who are making a difference</small></b></div></div><div className="hero-img"><img src={s.hero_image||'https://images.unsplash.com/photo-1489493585363-d69421e0edd3?auto=format&fit=crop&w=1500&q=88'} alt="Community support"/><aside><Heart fill="currentColor"/><b>Every Contribution<br/>Makes an Impact</b></aside></div></section>
<section className="values">{[[ShieldCheck,'Transparent','100% transparency in funds and operations'],[Users,'Accountable','We are accountable to donors and communities'],[Target,'Impact Driven','Focused on measurable and lasting impact'],[Heart,'Community First','We work with communities, not just for them']].map(([I,t,p])=><article><I/><div><b>{t}</b><p>{p}</p></div></article>)}</section>
<section className="impact"><h2>Our Impact in Numbers</h2><div>{[['25,000+','Lives Impacted'],['150+','Projects Completed'],['500+','Active Volunteers'],['50+','Communities Reached']].map((x,i)=><article><Heart fill="currentColor"/><b>{s[['lives','projects','volunteers','communities'][i]]||x[0]}+</b><span>{x[1]}</span></article>)}</div></section>
<section id="causes" className="section"><div className="section-title"><div><small>LIVE FUNDRAISING CAMPAIGNS</small><h2>Our Causes</h2><p className="live-note"><span/> Live campaign totals refresh automatically</p></div><div className="campaign-total"><b>{money(data.campaignSummary?.raised||0)}</b><small>received of {money(data.campaignSummary?.goal||0)} total goal</small></div></div><div className="cards">{data.causes.map(c=><Cause c={c} key={c.id} donate={()=>setDonate(c)}/>)}</div>{data.recentDonations?.length>0&&<div className="recent-donations"><h3>Recent contributions</h3><div>{data.recentDonations.map(d=><article key={d.id}><Heart fill="currentColor"/><span><b>{d.donor}</b><small>{d.cause_title||'General Fund'} · {new Date(d.paid_at||d.created_at).toLocaleDateString('en-IN')}</small></span><strong>{money(d.amount)}</strong></article>)}</div></div>}</section>
<section id="about" className="split section"><div><small>ABOUT US</small><h2>{s.about_title||'We Are Here to Create Lasting Change'}</h2><p>{s.about_text}</p>{['Transparency and accountability','Compassion and integrity','Community-led sustainable action'].map(x=><p className="tick"><Check/> {x}</p>)}</div><div className="video"><img src={s.about_image||'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1200&q=85'} alt="About our work"/><button><Play fill="currentColor"/></button></div></section>
<section id="events" className="section updates-section"><div className="section-title"><div><small>STAY CONNECTED</small><h2>Events & Latest News</h2><p>Live updates managed from the admin dashboard.</p></div></div><div className="updates-grid"><VerticalFeed title="Upcoming Events" icon={CalendarDays} items={data.events} kind="event"/><VerticalFeed title="Latest News" icon={Newspaper} items={data.news} kind="news"/></div></section>
{s.show_gallery!=='false'&&<section id="gallery" className="section"><div className="section-title"><div><small>OUR WORK IN PICTURES</small><h2>Gallery</h2></div></div><div className="gallery-grid">{data.gallery.map(g=><figure key={g.id}><img src={g.image} alt={g.title}/><figcaption><b>{g.title}</b><span>{g.caption}</span></figcaption></figure>)}</div></section>}
{s.show_team!=='false'&&<section id="team" className="section soft-section"><div className="section-title"><div><small>PEOPLE BEHIND THE MISSION</small><h2>Our Team</h2></div></div><div className="team-grid">{data.team_members.map(x=><article key={x.id}><img src={x.image} alt={x.name}/><h3>{x.name}</h3><b>{x.role}</b><p>{x.bio}</p></article>)}</div></section>}
{s.show_partners!=='false'&&<section className="section partners-section"><div className="section-title"><div><small>TRUSTED COLLABORATIONS</small><h2>Partners & Sponsors</h2></div></div><div className="partners-grid">{data.partners.map(x=><a key={x.id} href={x.website||'#'}><img src={x.logo} alt={x.name}/><span>{x.name}</span></a>)}</div></section>}
<section id="volunteer" className="volunteer section"><div><small>GET INVOLVED</small><h2>Your time can change a life.</h2><p>Join teaching, healthcare, environment, fundraising or event support programs.</p></div><SmartForm endpoint="/api/volunteers" notify={notify} fields={[['name','Full name'],['email','Email address','email'],['phone','Phone number'],['interest','Area of interest'],['message','How would you like to help?','textarea']]} button="Apply as Volunteer"/></section>
<section id="stories" className="stories section"><div className="section-title"><div><small>REAL VOICES</small><h2>Stories of Change</h2></div><div><button onClick={()=>setStory((story-1+data.stories.length)%data.stories.length)}><ChevronLeft/></button><button onClick={()=>setStory((story+1)%data.stories.length)}><ChevronRight/></button></div></div>{current&&<article><p>“{current.quote}”</p><div><img src={current.image}/><b>{current.name}<small>{current.role}</small></b></div></article>}</section>
<section id="contact" className="contact section"><div><small>CONTACT US</small><h2>Let’s create impact together.</h2><p><MapPin/> {s.address}</p><p><Phone/> {s.phone}</p><p><Mail/> {s.email}</p></div><SmartForm endpoint="/api/contacts" notify={notify} fields={[['name','Full name'],['email','Email address','email'],['phone','Phone number'],['subject','Subject'],['message','Your message','textarea']]} button="Send Message"/></section>
<section className="newsletter"><div><Mail/><b>Stay Updated with Our Work<small>Get project updates and stories in your inbox.</small></b></div><SmartForm endpoint="/api/subscribers" notify={notify} inline fields={[['email','Enter your email address','email']]} button="Subscribe"/></section></main><footer><div><h3>Hope & Heart Foundation</h3><p>{s.footer_text||'Together, let’s build a better world for today and tomorrow.'}</p></div><div><b>Quick Links</b><a href="#causes">Causes</a><a href="#events">Events</a><a href="#volunteer">Volunteer</a></div><div><b>Contact</b><span>{s.address}</span><span>{s.phone}</span><span>{s.email}</span></div></footer>{donate&&<Donation c={donate} close={()=>setDonate(null)} notify={notify} onSuccess={load}/>} {toast&&<div className="toast"><Check/> {toast}</div>}</>}
function VerticalFeed({title,icon:Icon,items=[],kind}){const doubled=items.length>1?[...items,...items]:items;return <section id={kind==='news'?'news':undefined} className="vertical-feed"><header><span><Icon/></span><div><small>{kind==='event'?'UPCOMING':'NEWSROOM'}</small><h3>{title}</h3></div><a href={kind==='event'?'#contact':'#news'}>View all <ArrowRight/></a></header><div className="feed-window"><div className={items.length>1?'feed-track moving':'feed-track'}>{doubled.map((item,i)=>kind==='event'?<article className="feed-card event-feed" key={`${item.id}-${i}`}><div className="date-tile"><b>{new Date(item.event_date).toLocaleDateString('en-IN',{day:'2-digit'})}</b><small>{new Date(item.event_date).toLocaleDateString('en-IN',{month:'short'}).toUpperCase()}</small></div><img src={item.image}/><div><small><Clock/> {new Date(item.event_date).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</small><h4>{item.title}</h4><p><MapPin/> {item.location}</p><span>{item.description}</span></div></article>:<article className="feed-card news-feed" key={`${item.id}-${i}`}><img src={item.image}/><div><small>{item.category||'Update'} · {new Date(item.published_at||item.created_at).toLocaleDateString('en-IN')}</small><h4>{item.title}</h4><p>{item.summary}</p><a href={item.link||'#contact'}>Read more <ArrowRight/></a></div></article>)}</div>{!items.length&&<div className="empty">No published {kind==='event'?'events':'news'} yet.</div>}</div></section>}
function Cause({c,donate}){const pct=Math.min(100,Math.round(Number(c.raised||0)/Number(c.goal||1)*100));return <article className="card cause"><div className="campaign-image"><img src={c.image}/><span className={`campaign-status ${String(c.status).toLowerCase()}`}>{pct>=100?'Goal reached':c.status}</span></div><div><small>{c.category}</small><h3>{c.title}</h3><p>{c.description}</p><div className="campaign-money"><b>{money(c.raised)}</b><span>of {money(c.goal)}</span></div><div className="bar" aria-label={`${pct}% funded`}><i style={{width:`${pct}%`}}/></div><div className="raised"><b>{pct}% funded</b><span>{Number(c.donor_count||0).toLocaleString('en-IN')} donors</span></div><button className="btn primary" onClick={donate} disabled={pct>=100}>{pct>=100?'Campaign Funded':'Donate Now'}</button></div></article>}
function SmartForm({endpoint,fields,button,notify,inline}){const[sub,setSub]=useState(false);const send=async e=>{e.preventDefault();setSub(true);try{await api(endpoint,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});e.currentTarget.reset();notify('Submitted successfully. Thank you!')}catch(x){notify(x.message)}finally{setSub(false)}};return <form onSubmit={send} className={inline?'inline':''}>{fields.map(([n,p,t])=>t==='textarea'?<textarea name={n} placeholder={p} required/>:<input name={n} type={t||'text'} placeholder={p} required/>)}<button className="btn primary" disabled={sub}>{sub?'Sending…':button}</button></form>}
function loadRazorpay(){return new Promise(resolve=>{if(window.Razorpay)return resolve(true);const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.body.appendChild(s)})}
function Donation({c,close,notify,onSuccess}){const[amount,setAmount]=useState(1000),[loading,setLoading]=useState(false);const send=async e=>{e.preventDefault();setLoading(true);try{const form=Object.fromEntries(new FormData(e.currentTarget));const ready=await loadRazorpay();if(!ready)throw new Error('Payment window could not be loaded. Please check your connection.');const order=await api('/api/donations',{method:'POST',body:JSON.stringify({...form,amount:Number(amount),cause_id:c.id||null,anonymous:!!form.anonymous})});const payment=new window.Razorpay({key:order.key_id,amount:order.amount,currency:order.currency,name:'Hope & Heart Foundation',description:c.title?`Donation for ${c.title}`:'General Donation',order_id:order.order_id,prefill:{name:form.donor_name,email:form.email},theme:{color:'#149447'},handler:async response=>{try{const verified=await api('/api/donations/verify',{method:'POST',body:JSON.stringify(response)});notify(`Payment successful. Receipt ID: ${verified.donation_id}`);onSuccess?.();close()}catch(x){notify(x.message)}},modal:{ondismiss:()=>setLoading(false)}});payment.on('payment.failed',r=>{notify(r.error?.description||'Payment failed. Please try again.');setLoading(false)});payment.open()}catch(x){notify(x.message);setLoading(false)}};return <div className="modal"><div><button className="close" onClick={close}><X/></button><Heart className="modal-heart" fill="currentColor"/><h2>Make a Difference Today</h2><p>{c.title?`Supporting ${c.title}`:'Support our general fund'}</p><form onSubmit={send}><div className="amounts">{[500,1000,2500,5000].map(x=><button key={x} type="button" className={Number(amount)===x?'active':''} onClick={()=>setAmount(x)}>₹{x}</button>)}</div><input type="number" min="100" value={amount} onChange={e=>setAmount(e.target.value)}/><input name="donor_name" placeholder="Full name" required/><input name="email" type="email" placeholder="Email address" required/><input name="frequency" type="hidden" value="One-time"/><label><input name="anonymous" type="checkbox"/> Donate anonymously</label><button className="btn primary" disabled={loading}>{loading?'Opening secure payment…':`Donate ${money(amount)}`}</button></form><small>Secure payment powered by Razorpay. A verified receipt ID is shown after payment.</small></div></div>}
function Admin(){const[token,setToken]=useState(()=>localStorage.getItem('adminToken')),[data,setData]=useState(null),[tab,setTab]=useState('overview'),[msg,setMsg]=useState(''),[loadError,setLoadError]=useState('');const load=async()=>{setLoadError('');try{const[o,d]=await Promise.all([api('/api/admin/overview'),api('/api/admin/data')]);setData({...d,overview:o})}catch(error){console.error('Dashboard loading failed:',error);const message=error?.message||'Unable to load dashboard.';if(message==='Administrator authentication required.'||message==='Invalid or expired administrator session.'){localStorage.removeItem('adminToken');setToken(null);return}setLoadError(message)}};useEffect(()=>{if(token)load()},[token]);if(!token)return <AdminLogin done={t=>{localStorage.setItem('adminToken',t);setToken(t)}}/>;if(loadError)return <div className="loading"><h2>Dashboard could not load</h2><p>{loadError}</p><div className="actions"><button className="btn primary" onClick={load}>Try Again</button><button className="btn ghost" onClick={()=>{localStorage.removeItem('adminToken');setToken(null)}}>Sign Out</button></div></div>;if(!data)return <div className="loading">Loading dashboard…</div>;const notify=x=>{setMsg(x);setTimeout(()=>setMsg(''),2500)};return <div className="admin"><aside><a className="brand" href="#home"><b>♡</b><span>Hope & Heart<small>ADMIN PANEL</small></span></a>{['overview','causes','stories','events','news','gallery','team_members','partners','donations','volunteers','contacts','subscribers','settings'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}<button onClick={()=>{localStorage.removeItem('adminToken');setToken(null)}}><LogOut/> Logout</button></aside><section><header><div><small>ADMINISTRATION</small><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1></div><a href="#home" className="btn ghost">View Website</a></header>{tab==='overview'&&<Overview o={data.overview}/>} {['causes','stories','events','news','gallery','team_members','partners'].includes(tab)&&<Manager type={tab} rows={data[tab]||[]} reload={load} notify={notify}/>} {['donations','subscribers'].includes(tab)&&<DataTable rows={data[tab]||[]}/>} {['volunteers','contacts'].includes(tab)&&<StatusTable type={tab} rows={data[tab]||[]} reload={load} notify={notify}/>} {tab==='settings'&&<Settings values={data.settings||{}} reload={load} notify={notify}/>}</section>{msg&&<div className="toast">{msg}</div>}</div>}
function AdminLogin({done}){const[err,setErr]=useState('');const send=async e=>{e.preventDefault();try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});done(r.token)}catch(x){setErr(x.message)}};return <div className="login"><form onSubmit={send}><div className="brand"><b>♡</b><span>Hope & Heart<small>ADMIN LOGIN</small></span></div><h1>Welcome back</h1><input name="email" type="email" placeholder="Admin email"/><input name="password" type="password" placeholder="Password"/><button className="btn primary">Sign In</button>{err&&<p>{err}</p>}<a href="#home">← Return to website</a></form></div>}
function Overview({o}){return <><div className="stats">{Object.entries(o.totals).map(([k,v])=><article><small>{k}</small><b>{k==='donations'?money(v):v}</b></article>)}</div><div className="panel"><h2>Recent Donations</h2><DataTable rows={o.recent}/></div></>}
function DataTable({rows}){if(!rows.length)return <div className="empty">No records yet.</div>;const keys=Object.keys(rows[0]).filter(k=>!['image','description','quote','message'].includes(k)).slice(0,7);return <div className="table"><table><thead><tr>{keys.map(k=><th>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map(r=><tr>{keys.map(k=><td>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div>}
function ImageField({name,defaultValue='',required=true}){const[value,setValue]=useState(defaultValue),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{setValue(defaultValue||'')},[defaultValue]);const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const result=await uploadImage(file);setValue(result.url)}catch(err){setError(err.message||'Image upload failed.')}finally{setBusy(false);e.target.value=''}};return <div className="image-field"><input name={name} type="url" value={value} onChange={e=>setValue(e.target.value)} placeholder={`${name.replaceAll('_',' ')} URL`} required={required}/><label className={`btn ghost${busy?' disabled':''}`}>{busy?'Uploading…':'Upload image'}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={upload} disabled={busy} hidden/></label>{value&&<div className="image-preview"><img src={value} alt={`${name} preview`}/><button type="button" className="danger" onClick={()=>setValue('')}>Remove</button></div>}{error&&<p className="form-error">{error}</p>}</div>}
function Manager({type,rows,reload,notify}){const fields={causes:['title','category','description','image','raised','goal','status','featured'],stories:['name','role','quote','image','published'],events:['title','event_date','location','description','image','capacity','published'],news:['title','category','summary','content','image','link','published_at','published'],gallery:['title','category','image','caption','sort_order','published'],team_members:['name','role','bio','image','email','sort_order','published'],partners:['name','logo','website','sort_order','published']}[type]||[];const[editing,setEditing]=useState(null);const save=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.currentTarget));for(const k of ['raised','goal','capacity','sort_order'])if(k in x)x[k]=Number(x[k]||0);for(const k of ['published','featured'])if(k in x)x[k]=['1','true','on'].includes(String(x[k]));const url=editing?`/api/admin/${type}/${editing.id}`:`/api/admin/${type}`;await api(url,{method:editing?'PUT':'POST',body:JSON.stringify(x)});e.currentTarget.reset();setEditing(null);await reload();notify(editing?'Item updated':'Item created')};const del=async id=>{if(!confirm('Delete this item permanently?'))return;await api(`/api/admin/${type}/${id}`,{method:'DELETE'});await reload();notify('Item deleted')};const label=f=>f.replaceAll('_',' ');return <><form key={editing?.id||'new'} className="editor" onSubmit={save}><h2><Plus/> {editing?'Edit':'Add'} {type==='news'?'news item':type.slice(0,-1)}</h2>{fields.map(f=>(f==='image'||f==='logo')?<ImageField key={f} name={f} defaultValue={editing?.[f]??''} required/>:f==='description'||f==='quote'||f==='summary'||f==='content'||f==='caption'||f==='bio'?<textarea key={f} name={f} placeholder={label(f)} required={!['content'].includes(f)} defaultValue={editing?.[f]??''}/>:f==='published'||f==='featured'?<label key={f} className="check-field"><input name={f} type="checkbox" defaultChecked={editing?!!editing[f]:true}/> {label(f)}</label>:<input key={f} name={f} type={f.includes('date')?'datetime-local':f==='raised'||f==='goal'||f==='capacity'||f==='sort_order'?'number':f==='email'?'email':f==='link'||f==='website'?'url':'text'} placeholder={label(f)} required={!['raised','link','email','website'].includes(f)} defaultValue={editing?.[f]??(f==='status'?'Active':'')}/>)}<div className="editor-actions"><button className="btn primary">{editing?'Update':'Save'}</button>{editing&&<button type="button" className="btn ghost" onClick={()=>setEditing(null)}>Cancel</button>}</div></form><div className="manage-grid">{rows.map(r=><article key={r.id}>{(r.image||r.logo)&&<img src={r.image||r.logo} alt={r.title||r.name||'Item'}/>}<div><h3>{r.title||r.name}</h3><p>{r.category||r.role||r.location}</p><div className="row-actions"><button className="btn ghost" onClick={()=>setEditing(r)}>Edit</button><button className="danger" onClick={()=>del(r.id)}><Trash2/> Delete</button></div></div></article>)}</div></>} 
function StatusTable({type,rows,reload,notify}){const change=async(id,status)=>{await api(`/api/admin/${type}/${id}/status`,{method:'PUT',body:JSON.stringify({status})});reload();notify('Status updated')};return <div className="panel"><DataTable rows={rows}/>{rows.map(r=><div className="status-row"><b>{r.name}</b><span>{r.email}</span><select value={r.status} onChange={e=>change(r.id,e.target.value)}><option>New</option><option>Pending</option><option>Approved</option><option>Rejected</option><option>Resolved</option></select></div>)}</div>}
function Settings({values,reload,notify}){const[busy,setBusy]=useState(false);const imageKeys=new Set(['logo','favicon','hero_image','about_image','donation_qr','footer_logo']);const save=async e=>{e.preventDefault();setBusy(true);try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});await reload();notify('Settings saved')}catch(error){notify(error.message||'Unable to save settings.')}finally{setBusy(false)}};return <form className="editor settings" onSubmit={save}>{Object.entries(values).map(([k,v])=>imageKeys.has(k)?<label key={k}>{k.replaceAll('_',' ')}<ImageField name={k} defaultValue={v} required={false}/></label>:<label key={k}>{k.replaceAll('_',' ')}<input name={k} defaultValue={v}/></label>)}<button className="btn primary" disabled={busy}>{busy?'Saving…':'Save Settings'}</button></form>}
createRoot(document.getElementById('root')).render(<App/>);
cd HEART
