import { createClient } from '@supabase/supabase-js';

const url = process.env.SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

const out = (res, status, data) => res.status(status).json(data);

export default async function handler(req, res) {

      res.setHeader(
              'Cache-Control',
                'no-store, no-cache, must-revalidate, proxy-revalidate'
                );
                res.setHeader('Pragma', 'no-cache');
                res.setHeader('Expires', '0');
      
  if (req.method !== 'GET') {
      return out(res, 405, { error: 'Method not allowed.' });
        }

          if (!url || !serviceKey) {
              return out(res, 500, {
                    error: 'Supabase server environment variables are missing.'
                        });
                          }

                            const supabase = createClient(url, serviceKey, {
                                auth: { persistSession: false }
                                  });

                                    try {
                                        const [
                                              settingsResult,
                                                    causes,
                                                          stories,
                                                                events,
                                                                      news,
                                                                            gallery,
                                                                                  team,
                                                                                        partners,
                                                                                              paidDonations
                                                                                                  ] = await Promise.all([
                                                                                                        supabase.from('settings').select('key,value'),
                                                                                                              supabase
                                                                                                                      .from('causes')
                                                                                                                              .select('*')
                                                                                                                                      .eq('status', 'Active')
                                                                                                                                              .order('id', { ascending: false }),
                                                                                                                                                    supabase
                                                                                                                                                            .from('stories')
                                                                                                                                                                    .select('*')
                                                                                                                                                                            .eq('published', true)
                                                                                                                                                                                    .order('id', { ascending: false }),
                                                                                                                                                                                          supabase
                                                                                                                                                                                                  .from('events')
                                                                                                                                                                                                          .select('*')
                                                                                                                                                                                                                  .eq('published', true)
                                                                                                                                                                                                                          .order('event_date', { ascending: true }),
                                                                                                                                                                                                                                supabase
                                                                                                                                                                                                                                        .from('news')
                                                                                                                                                                                                                                                .select('*')
                                                                                                                                                                                                                                                        .eq('published', true)
                                                                                                                                                                                                                                                                .order('published_at', { ascending: false }),
                                                                                                                                                                                                                                                                      supabase
                                                                                                                                                                                                                                                                              .from('gallery')
                                                                                                                                                                                                                                                                                      .select('*')
                                                                                                                                                                                                                                                                                              .eq('published', true)
                                                                                                                                                                                                                                                                                                      .order('sort_order', { ascending: true }),
                                                                                                                                                                                                                                                                                                            supabase
                                                                                                                                                                                                                                                                                                                    .from('team_members')
                                                                                                                                                                                                                                                                                                                            .select('*')
                                                                                                                                                                                                                                                                                                                                    .eq('published', true)
                                                                                                                                                                                                                                                                                                                                            .order('sort_order', { ascending: true }),
                                                                                                                                                                                                                                                                                                                                                  supabase
                                                                                                                                                                                                                                                                                                                                                          .from('partners')
                                                                                                                                                                                                                                                                                                                                                                  .select('*')
                                                                                                                                                                                                                                                                                                                                                                          .eq('published', true)
                                                                                                                                                                                                                                                                                                                                                                                  .order('sort_order', { ascending: true }),
                                                                                                                                                                                                                                                                                                                                                                                        supabase
                                                                                                                                                                                                                                                                                                                                                                                                .from('donations')
                                                                                                                                                                                                                                                                                                                                                                                                        .select(
                                                                                                                                                                                                                                                                                                                                                                                                                  'id,amount,cause_id,donor_name,anonymous,paid_at,created_at'
                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                  .eq('status', 'Successful')
                                                                                                                                                                                                                                                                                                                                                                                                                                          .order('paid_at', { ascending: false })
                                                                                                                                                                                                                                                                                                                                                                                                                                              ]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                  const results = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                        settingsResult,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              causes,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stories,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          events,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                news,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gallery,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            team,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  partners,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        paidDonations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const failed = results.find(result => result.error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (failed?.error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          throw failed.error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const settings = Object.fromEntries(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (settingsResult.data || []).map(row => [row.key, row.value])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const donationRows = paidDonations.data || [];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const donorCounts = donationRows.reduce((counts, row) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (row.cause_id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  counts[row.cause_id] = (counts[row.cause_id] || 0) + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return counts;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, {});

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const causeRows = (causes.data || []).map(cause => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...cause,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  donor_count: donorCounts[cause.id] || 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const causeNames = Object.fromEntries(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                causeRows.map(cause => [cause.id, cause.title])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const recentDonations = donationRows.slice(0, 6).map(donation => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              id: donation.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    amount: donation.amount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          paid_at: donation.paid_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                created_at: donation.created_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      donor: donation.anonymous
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? 'Anonymous donor'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : String(donation.donor_name || 'Supporter').split(' ')[0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cause_title: donation.cause_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? causeNames[donation.cause_id]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : 'General Fund'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const campaignSummary = causeRows.reduce(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          (total, cause) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  raised: total.raised + Number(cause.raised || 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          goal: total.goal + Number(cause.goal || 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  donors: total.donors + Number(cause.donor_count || 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { raised: 0, goal: 0, donors: 0 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return out(res, 200, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            settings,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  causes: causeRows,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        stories: stories.data || [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              events: events.data || [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    news: news.data || [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          gallery: gallery.data || [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                team_members: team.data || [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      partners: partners.data || [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            recentDonations,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  campaignSummary
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Public API error:', error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return out(res, 500, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      error: error?.message || 'Unable to load public website data.'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }